<?php
namespace App\Controllers\SchoolOwner;
use App\Controllers\BaseController;
use App\Models\ServiceOrderModel;
use App\Models\ServiceBillingSettingModel;
class ServiceBilling extends BaseController
{
    public function __construct(private ?ServiceOrderModel $orders=null){$this->orders??=new ServiceOrderModel();}
    public function index(){ $data['orders']=$this->orders->select('service_orders.*, examination_exams.title exam_title')->join('examination_exams','examination_exams.id=service_orders.exam_id','left')->where('service_orders.school_id',(int)session('school_id'))->orderBy('service_orders.id','DESC')->findAll();return $this->render('বিল ও পেমেন্ট','school_owner/service_billing/index',$data); }
    public function show(string $token){$order=$this->orders->where(['token'=>$token,'school_id'=>(int)session('school_id')])->first();if(!$order)return redirect()->to('school-owner/billing')->with('error','বিল পাওয়া যায়নি।');$target=null;if(in_array($order->status,['paid','completed'],true)&&$order->reference_id){if($order->service==='SEAT_PLAN'){$r=(new \App\Modules\examination\Models\ExamSeatPlanModel())->find($order->reference_id);$target=$r?'examination/seat-plans/view/'.$r->token:null;}elseif($order->service==='ADMIT_CARD'){$r=(new \App\Modules\examination\Models\AdmitCardSettingModel())->find($order->reference_id);$target=$r?'examination/admit-cards/view/'.$r->token:null;}elseif($order->service==='RESULT')$target='examination/result-wizard/step/6';}$paymentSettings=[];foreach((new ServiceBillingSettingModel())->whereIn('setting_key',['payment_method_name','payment_account_number','payment_account_type','payment_instructions'])->findAll() as $setting){$paymentSettings[$setting->setting_key]=$setting->setting_value;}return $this->render('বিলের বিস্তারিত','school_owner/service_billing/show',['order'=>$order,'target'=>$target,'paymentSettings'=>$paymentSettings]);}
    public function manual(string $token){$setting=new ServiceBillingSettingModel();if((int)$setting->value('manual_payment_enabled',1)!==1)return redirect()->back()->with('error','Manual payment বর্তমানে বন্ধ আছে।');$order=$this->orders->where(['token'=>$token,'school_id'=>(int)session('school_id')])->first();if(!$order||!in_array($order->status,['draft','payment_pending'],true))return redirect()->back()->with('error','এই বিলের পেমেন্ট নেওয়া যাবে না।');$transaction=trim((string)$this->request->getPost('transaction_id'));if($transaction==='')return redirect()->back()->with('error','Transaction ID দিন।');$this->orders->update($order->id,['status'=>'payment_pending','payment_method'=>'manual','transaction_id'=>$transaction,'payment_note'=>trim((string)$this->request->getPost('payment_note'))]);return redirect()->to('school-owner/billing')->with('success','পেমেন্ট তথ্য পাঠানো হয়েছে। Admin যাচাই করলে Final Result চালু হবে।');}
    public function legacy(...$ignored){return redirect()->to('school-owner/billing')->with('info','Subscription plans have been replaced by pay-per-service billing.');}
    private function render(string $title,string $view,array $data=[]){return view('header',['page_title'=>$title,'body_class'=>'nav-md','admin_area'=>'yes']).view($view,$data).view('footer',['admin_area'=>'yes']);}
}
