<?php $v=static fn($key,$default='')=>old($key,$item->{$key}??$default); ?>
<div class="right_col" role="main"><h2 class="mb-3"><?= $item?'Edit':'Create' ?> Admission Circular</h2><div class="card shadow-sm"><div class="card-body"><?= form_open('school/admission/circulars/save') ?><input type="hidden" name="token" value="<?= esc($item->token??'') ?>"><div class="row">
<div class="col-md-6 mb-3"><label>School *</label><select id="admission-school" class="form-control" name="school_id" required><?php foreach($schools as $s): ?><option value="<?= $s->id ?>" <?= (string)$v('school_id')===(string)$s->id?'selected':'' ?>><?= esc($s->name) ?></option><?php endforeach ?></select></div>
<div class="col-md-6 mb-3"><label>Admission Session *</label><select id="admission-session" class="form-control" name="admission_session_id" required><?php foreach($sessionItems as $s): ?><option value="<?= $s->id ?>" <?= (string)$v('admission_session_id')===(string)$s->id?'selected':'' ?>><?= esc($s->title) ?></option><?php endforeach ?></select></div>
<div class="col-md-8 mb-3"><label>Title *</label><input class="form-control" name="title" value="<?= esc($v('title')) ?>" required></div>
<div class="col-md-4 mb-3"><label>Status *</label><select class="form-control" name="status"><?php foreach(['draft','published','closed'] as $status): ?><option value="<?= $status ?>" <?= $v('status','draft')===$status?'selected':'' ?>><?= ucfirst($status) ?></option><?php endforeach ?></select></div>
<div class="col-md-6 mb-3"><label>Class *</label><select id="admission-class" class="form-control" name="class_id" required><?php foreach($academic['classes'] as $c): ?><option value="<?= $c->id ?>" <?= (string)$v('class_id')===(string)$c->id?'selected':'' ?>><?= esc($c->title) ?></option><?php endforeach ?></select></div>
<div class="col-md-6 mb-3"><label>Shift</label><select id="admission-shift" class="form-control" name="shift_id"><option value="">All / none</option><?php foreach($academic['shifts'] as $s): ?><option value="<?= $s->id ?>" <?= (string)$v('shift_id')===(string)$s->id?'selected':'' ?>><?= esc($s->title) ?></option><?php endforeach ?></select></div>
<div class="col-md-3 mb-3"><label>Available Seats *</label><input type="number" min="0" class="form-control" name="available_seats" value="<?= esc($v('available_seats',0)) ?>" required></div>
<div class="col-md-3 mb-3"><label>Minimum Age</label><input type="number" min="0" step="0.1" class="form-control" name="minimum_age" value="<?= esc($v('minimum_age')) ?>"></div>
<div class="col-md-3 mb-3"><label>Maximum Age</label><input type="number" min="0" step="0.1" class="form-control" name="maximum_age" value="<?= esc($v('maximum_age')) ?>"></div>
<div class="col-md-3 mb-3"><label>Lottery Required *</label><select class="form-control" name="lottery_required"><option value="0" <?= !$v('lottery_required',0)?'selected':'' ?>>No</option><option value="1" <?= $v('lottery_required',0)?'selected':'' ?>>Yes</option></select></div>
<?php foreach(['application_start'=>'Application Start *','application_deadline'=>'Application Deadline *'] as $key=>$label): ?><div class="col-md-6 mb-3"><label><?= $label ?></label><input type="datetime-local" class="form-control" name="<?= $key ?>" value="<?= esc($v($key)?date('Y-m-d\TH:i',strtotime($v($key))):'') ?>" required></div><?php endforeach ?>
<div class="col-md-6 mb-3"><label>Application Fee</label><input type="number" min="0" step="0.01" class="form-control" name="application_fee" value="<?= esc($v('application_fee',0)) ?>"></div><div class="col-md-6 mb-3"><label>Admission Fee</label><input type="number" min="0" step="0.01" class="form-control" name="admission_fee" value="<?= esc($v('admission_fee',0)) ?>"></div>
<div class="col-12 mb-3"><label>Description</label><textarea class="form-control" name="description" rows="3"><?= esc($v('description')) ?></textarea></div><div class="col-md-6 mb-3"><label>Instructions</label><textarea class="form-control" name="instructions" rows="4"><?= esc($v('instructions')) ?></textarea></div><div class="col-md-6 mb-3"><label>Required Documents</label><textarea class="form-control" name="required_documents" rows="4"><?= esc($v('required_documents')) ?></textarea></div>
</div><button class="btn btn-primary">Save circular</button> <a class="btn btn-light" href="<?= base_url('school/admission/circulars') ?>">Cancel</a><?= form_close() ?></div></div></div>
<script>document.getElementById('admission-school').addEventListener('change',async function(){const d=await fetch('<?= base_url('school/admission/academic-data') ?>/'+this.value).then(r=>r.json());const fill=(id,rows,blank='')=>document.getElementById(id).innerHTML=blank+rows.map(x=>`<option value="${x.id}">${x.title}</option>`).join('');fill('admission-session',d.sessions);fill('admission-class',d.classes);fill('admission-shift',d.shifts,'<option value="">All / none</option>');});</script>
