<?= get_system_message() ?>
<?php
$map=[]; foreach($settings as $s)$map[$s->setting_key]=$s->setting_value;
$pending=array_values(array_filter($orders,static fn($o)=>$o->status==='payment_pending'||($o->status==='draft'&&(float)$o->total<=0)));
$statusMeta=['draft'=>['Waiting for payment','secondary'],'payment_pending'=>['Needs approval','warning'],'paid'=>['Paid','success'],'completed'=>['Completed','primary'],'cancelled'=>['Cancelled','danger']];
?>
<style>.billing-admin .metric{border:0;border-radius:16px;box-shadow:0 5px 18px rgba(31,50,81,.08)}.billing-admin .nav-pills .nav-link{font-weight:700}.billing-admin details>summary{cursor:pointer}.billing-admin .order-actions{min-width:210px}.billing-admin code{white-space:nowrap}</style>
<main class="billing-admin">
<div class="d-flex flex-wrap justify-content-between align-items-center gap-3 mb-4"><div><h2 class="mb-1">Pay-Per-Service Billing</h2><p class="text-muted mb-0">Set prices, review payment submissions, and control service access.</p></div><a class="btn btn-success btn-lg" href="<?=site_url('saas-admin/service-billing/approvals')?>"><i class="bi bi-check2-square"></i> Approval queue <?php if($pending):?><span class="badge bg-light text-success ms-1"><?=count($pending)?></span><?php endif?></a></div>

<div class="row g-3 mb-4"><div class="col-md-4"><div class="card metric"><div class="card-body"><div class="text-muted">Needs your approval</div><div class="display-6 fw-bold text-warning"><?=count($pending)?></div><small>Payments submitted by schools</small></div></div></div><div class="col-md-4"><div class="card metric"><div class="card-body"><div class="text-muted">Open orders</div><div class="display-6 fw-bold"><?=count(array_filter($orders,static fn($o)=>in_array($o->status,['draft','payment_pending'],true)))?></div><small>Draft and submitted orders</small></div></div></div><div class="col-md-4"><div class="card metric"><div class="card-body"><div class="text-muted">Approval value</div><div class="display-6 fw-bold">৳<?=number_format(array_sum(array_map(static fn($o)=>(float)$o->total,$pending)),2)?></div><small>Waiting for verification</small></div></div></div></div>

<ul class="nav nav-pills gap-2 mb-3" role="tablist"><li class="nav-item"><button class="nav-link active" data-bs-toggle="pill" data-bs-target="#orders">Orders &amp; approvals</button></li><li class="nav-item"><button class="nav-link" data-bs-toggle="pill" data-bs-target="#pricing">Pricing rules</button></li><li class="nav-item"><button class="nav-link" data-bs-toggle="pill" data-bs-target="#settings">General settings</button></li></ul>
<div class="tab-content">
<section class="tab-pane fade show active" id="orders"><div class="alert alert-info"><strong>How approval works:</strong> Draft means the school has not submitted payment. “Needs approval” means a transaction ID was submitted and SaaS Admin can approve it.</div><div class="card border-0 shadow-sm"><div class="card-header d-flex justify-content-between"><strong>Recent service orders</strong><a href="<?=site_url('saas-admin/service-billing/approvals')?>">Show only pending approvals</a></div><div class="card-body table-responsive"><table class="table table-hover align-middle"><thead><tr><th>Invoice / School</th><th>Service</th><th>Exam</th><th>Students</th><th>Charge</th><th>Status / Transaction</th><th>Admin action</th></tr></thead><tbody>
<?php foreach($orders as $o):$waiverReady=$o->status==='draft'&&(float)$o->total<=0;$meta=$waiverReady?['Waiver ready','info']:($statusMeta[$o->status]??[ucfirst($o->status),'secondary']);?><tr class="<?=($o->status==='payment_pending'||$waiverReady)?'table-warning':''?>"><td><strong><?=esc($o->invoice_no)?></strong><br><small><?=esc($o->school_name??'-')?></small></td><td><strong><?=esc($o->service)?></strong><?php if(!empty($o->service_mode)):?><br><small><?=esc($o->service_mode)?></small><?php endif?></td><td><?=esc($o->exam_title??'-')?></td><td><?=number_format((int)$o->student_count)?></td><td><strong>৳<?=number_format((float)$o->total,2)?></strong><?php if((float)$o->discount>0):?><br><small class="text-success">Waiver ৳<?=number_format((float)$o->discount,2)?></small><?php endif?></td><td><span class="badge bg-<?=$meta[1]?>"><?=$meta[0]?></span><br><small>TX: <code><?=esc($o->transaction_id??'-')?></code></small></td><td class="order-actions">
<?php if($o->status==='payment_pending'||$waiverReady):?><?=form_open('saas-admin/service-billing/approve/'.$o->id,['class'=>'d-inline'])?><button class="btn btn-success btn-sm" onclick="return confirm('Approve and enable this service?')"><i class="bi bi-check-lg"></i> <?=$waiverReady?'Grant access':'Approve payment'?></button><?=form_close()?><?php endif?>
<?php if(in_array($o->status,['draft','payment_pending'],true)):?><details class="mt-2"><summary class="text-primary small">Discount / cancel options</summary><div class="pt-2"><?=form_open('saas-admin/service-billing/adjust/'.$o->id)?><label class="small">Discount or waiver</label><input class="form-control form-control-sm mb-1" type="number" min="0" max="<?=$o->subtotal?>" step=".01" name="discount" value="<?=$o->discount?>"><input class="form-control form-control-sm mb-1" name="note" placeholder="Reason required" required><button class="btn btn-outline-primary btn-sm w-100">Save adjustment</button><?=form_close()?><?=form_open('saas-admin/service-billing/cancel/'.$o->id)?><button class="btn btn-outline-danger btn-sm w-100 mt-1" onclick="return confirm('Cancel this order?')">Cancel order</button><?=form_close()?></div></details><?php else:?><span class="text-muted small">No action required</span><?php endif?></td></tr><?php endforeach?>
<?php if(!$orders):?><tr><td colspan="7" class="text-center text-muted py-5">No service orders yet.</td></tr><?php endif?></tbody></table></div></div></section>

<section class="tab-pane fade" id="pricing"><div class="card border-0 shadow-sm"><div class="card-header"><strong>Admin-configurable pricing tiers</strong></div><div class="card-body table-responsive"><table class="table"><thead><tr><th>ID</th><th>Service</th><th>Mode</th><th>Calculation</th><th>Student range</th><th>Amount</th><th>Status</th></tr></thead><tbody><?php foreach($rules as $r):?><tr><td><?=$r->id?></td><td><?=esc($r->service)?></td><td><?=esc($r->service_mode??'-')?></td><td><?=esc($r->pricing_type)?></td><td><?=esc(($r->min_students??0).' - '.($r->max_students??'∞'))?></td><td>৳<?=number_format($r->amount,2)?></td><td><?=$r->status?'Active':'Disabled'?></td></tr><?php endforeach?></tbody></table><details><summary class="btn btn-outline-primary">Add or update a pricing tier</summary><?=form_open('saas-admin/service-billing/rule',['class'=>'row g-2 mt-3'])?><div class="col-md-1"><input class="form-control" name="id" placeholder="ID"></div><div class="col-md-2"><select class="form-select" name="service"><option>RESULT</option><option>SEAT_PLAN</option><option>ADMIT_CARD</option></select></div><div class="col-md-2"><select class="form-select" name="service_mode"><option>SELF_SERVICE</option><option>MANAGED_SERVICE</option></select></div><div class="col-md-2"><select class="form-select" name="pricing_type"><option>PER_STUDENT_TIER</option><option>FIXED_TIER</option><option>PER_STUDENT</option><option>FIXED</option><option>FREE</option></select></div><div class="col-md-1"><input class="form-control" type="number" name="min_students" placeholder="Min"></div><div class="col-md-1"><input class="form-control" type="number" name="max_students" placeholder="Max"></div><div class="col-md-2"><input class="form-control" type="number" step=".01" name="amount" placeholder="Amount" required></div><input type="hidden" name="sort_order" value="10"><input type="hidden" name="status" value="1"><div class="col-md-1"><button class="btn btn-primary w-100">Save</button></div><?=form_close()?></details></div></div></section>

<section class="tab-pane fade" id="settings"><div class="card border-0 shadow-sm"><div class="card-header"><strong>General billing settings</strong></div><div class="card-body"><?=form_open('saas-admin/service-billing/settings')?><div class="row g-3"><div class="col-md-3"><label class="form-label">Demo student limit</label><input class="form-control" type="number" name="demo_student_limit" value="<?=esc($map['demo_student_limit']??20)?>"></div><div class="col-md-3"><label class="form-label">Minimum RESULT charge</label><input class="form-control" type="number" name="result_minimum_charge" value="<?=esc($map['result_minimum_charge']??1500)?>"></div><div class="col-md-3"><label class="form-label">Minimum charge</label><select class="form-select" name="result_minimum_enabled"><option value="1" <?=($map['result_minimum_enabled']??1)==1?'selected':''?>>Enabled</option><option value="0" <?=($map['result_minimum_enabled']??1)==0?'selected':''?>>Disabled</option></select></div><div class="col-md-3"><label class="form-label">Manual payment submission</label><select class="form-select" name="manual_payment_enabled"><option value="1" <?=($map['manual_payment_enabled']??1)==1?'selected':''?>>Enabled</option><option value="0" <?=($map['manual_payment_enabled']??1)==0?'selected':''?>>Disabled</option></select></div></div><hr class="my-4"><h5>Manual payment destination</h5><p class="text-muted">These details are shown to the school before it submits a transaction ID.</p><div class="row g-3"><div class="col-md-4"><label class="form-label">Payment method</label><input class="form-control" name="payment_method_name" value="<?=esc($map['payment_method_name']??'')?>" placeholder="e.g. bKash or Nagad"></div><div class="col-md-4"><label class="form-label">Account number</label><input class="form-control" name="payment_account_number" value="<?=esc($map['payment_account_number']??'')?>" placeholder="e.g. 01XXXXXXXXX"></div><div class="col-md-4"><label class="form-label">Account type/name</label><input class="form-control" name="payment_account_type" value="<?=esc($map['payment_account_type']??'')?>" placeholder="e.g. Merchant / Personal"></div><div class="col-12"><label class="form-label">Payment instructions</label><textarea class="form-control" name="payment_instructions" rows="3" placeholder="Any reference, counter number, or special instruction"><?=esc($map['payment_instructions']??'')?></textarea></div></div><button class="btn btn-primary mt-3">Save settings</button><?=form_close()?></div></div></section>
</div></main>
