<?php
namespace App\Controllers\SaasAdmin;
use App\Controllers\BaseController;
use App\Models\ServiceBillingSettingModel;
use App\Models\ServiceOrderModel;
use App\Models\ServicePricingRuleModel;
class ServiceBilling extends BaseController
{
    public function __construct(private ?ServicePricingRuleModel $rules=null,private ?ServiceBillingSettingModel $settings=null,private ?ServiceOrderModel $orders=null){$this->rules??=new ServicePricingRuleModel();$this->settings??=new ServiceBillingSettingModel();$this->orders??=new ServiceOrderModel();}
    public function index(){return $this->render('Service Pricing & Billing','saas_admin/service_billing/index',['rules'=>$this->rules->orderBy('service')->orderBy('sort_order')->findAll(),'settings'=>$this->settings->findAll(),'orders'=>$this->orders->select('service_orders.*, schools.name school_name, examination_exams.title exam_title')->join('schools','schools.id=service_orders.school_id','left')->join('examination_exams','examination_exams.id=service_orders.exam_id','left')->orderBy('service_orders.id','DESC')->findAll(100)]);}
    public function approvals(){
        $orders=$this->orders->select('service_orders.*, schools.name school_name, schools.phone school_phone, users.name submitted_by, examination_exams.title exam_title')
            ->join('schools','schools.id=service_orders.school_id','left')->join('users','users.id=service_orders.user_id','left')->join('examination_exams','examination_exams.id=service_orders.exam_id','left')
            ->groupStart()->where('service_orders.status','payment_pending')->orGroupStart()->where('service_orders.status','draft')->where('service_orders.total <=',0)->groupEnd()->groupEnd()
            ->orderBy('service_orders.updated_at','ASC')->findAll();
        return $this->render('Service Payment Approvals','saas_admin/service_billing/approvals',['orders'=>$orders]);
    }
    public function saveSettings(){foreach(['result_minimum_charge','result_minimum_enabled','demo_student_limit','manual_payment_enabled','payment_method_name','payment_account_number','payment_account_type','payment_instructions'] as $key){$value=trim((string)$this->request->getPost($key));$old=$this->settings->where('setting_key',$key)->first();$old?$this->settings->update($old->id,['setting_value'=>$value]):$this->settings->insert(['setting_key'=>$key,'setting_value'=>$value]);}return redirect()->back()->with('success','Billing settings saved.');}
    public function saveRule(){ $id=(int)$this->request->getPost('id');$service=strtoupper((string)$this->request->getPost('service'));$mode=$service==='RESULT'?strtoupper((string)$this->request->getPost('service_mode')):null;if($service==='RESULT'&&!in_array($mode,['SELF_SERVICE','MANAGED_SERVICE'],true))return redirect()->back()->with('error','Select a valid result service mode.');$data=['service'=>$service,'service_mode'=>$mode,'pricing_type'=>(string)$this->request->getPost('pricing_type'),'min_students'=>$this->nullableInt('min_students'),'max_students'=>$this->nullableInt('max_students'),'amount'=>(float)$this->request->getPost('amount'),'sort_order'=>(int)$this->request->getPost('sort_order'),'status'=>(int)$this->request->getPost('status')];$id?$this->rules->update($id,$data):$this->rules->insert($data);return redirect()->back()->with('success','Pricing rule saved.');}
    public function approve(int $id){$order=$this->orders->find($id);if(!$order)return redirect()->back()->with('error','Service order not found.');$canApprove=$order->status==='payment_pending'||($order->status==='draft'&&(float)$order->total<=0);if(!$canApprove)return redirect()->back()->with('error','Payment evidence or a full admin waiver is required before approval.');$ok=$this->orders->update($id,['status'=>'paid','paid_at'=>date('Y-m-d H:i:s'),'approved_by'=>(int)session('user_id')]);return redirect()->back()->with($ok?'success':'error',$ok?'Approved. The service is now available.':'Approval failed.');}
    public function cancel(int $id){$order=$this->orders->find($id);if(!$order)return redirect()->back()->with('error','Service order not found.');if(!in_array($order->status,['draft','payment_pending'],true))return redirect()->back()->with('error','A finalized order cannot be cancelled.');$ok=$this->orders->update($id,['status'=>'cancelled','approved_by'=>(int)session('user_id')]);return redirect()->back()->with($ok?'success':'error',$ok?'Order cancelled.':'Order cancellation failed.');}
    public function adjust(int $id){$order=$this->orders->find($id);if(!$order||in_array($order->status,['paid','completed','cancelled'],true))return redirect()->back()->with('error','Finalized order cannot be changed.');$note=trim((string)$this->request->getPost('note'));if($note==='')return redirect()->back()->with('error','A reason is required for discounts and waivers.');$discount=max(0,min((float)$order->subtotal,(float)$this->request->getPost('discount')));$this->orders->update($id,['discount'=>$discount,'total'=>(float)$order->subtotal-$discount,'payment_note'=>$note]);return redirect()->back()->with('success','Discount/waiver applied.');}
    private function nullableInt(string $key):?int{$v=$this->request->getPost($key);return $v===''||$v===null?null:(int)$v;}
    private function render(string $title,string $view,array $data=[]){return view('header',['page_title'=>$title,'body_class'=>'nav-md','admin_area'=>'yes']).view($view,$data).view('footer',['admin_area'=>'yes']);}
}
