<?php $v=static fn($key,$default='')=>old($key,$item->{$key}??$default); ?>
<div class="right_col" role="main"><h2 class="mb-3"><?= $item?'Edit':'Create' ?> Admission Session</h2>
<div class="card shadow-sm"><div class="card-body"><?= form_open('school/admission/sessions/save') ?><input type="hidden" name="token" value="<?= esc($item->token??'') ?>">
<div class="row">
 <div class="col-md-6 mb-3"><label>School *</label><select id="admission-school" name="school_id" class="form-control" required><?php foreach($schools as $s): ?><option value="<?= $s->id ?>" <?= (string)$v('school_id')===(string)$s->id?'selected':'' ?>><?= esc($s->name) ?></option><?php endforeach ?></select></div>
 <div class="col-md-6 mb-3"><label>Title *</label><input class="form-control" name="title" value="<?= esc($v('title')) ?>" placeholder="Admission 2027" required></div>
 <div class="col-md-6 mb-3"><label>Academic Session *</label><select id="academic-year" name="academic_year_id" class="form-control" data-selected="<?= esc($v('academic_year_id')) ?>" required><?php foreach($years as $y): ?><option value="<?= $y->id ?>" <?= (string)$v('academic_year_id')===(string)$y->id?'selected':'' ?>><?= esc($y->title) ?></option><?php endforeach ?></select></div>
 <div class="col-md-6 mb-3"><label>Status *</label><select name="status" class="form-control"><?php foreach(['draft','published','closed'] as $status): ?><option value="<?= $status ?>" <?= $v('status','draft')===$status?'selected':'' ?>><?= ucfirst($status) ?></option><?php endforeach ?></select></div>
 <?php foreach(['application_start'=>'Application Start *','application_end'=>'Application End *','admission_start'=>'Admission Start','admission_end'=>'Admission End'] as $key=>$label): ?><div class="col-md-6 mb-3"><label><?= $label ?></label><input type="datetime-local" class="form-control" name="<?= $key ?>" value="<?= esc($v($key)?date('Y-m-d\TH:i',strtotime($v($key))):'') ?>" <?= str_starts_with($label,'Application')?'required':'' ?>></div><?php endforeach ?>
</div><button class="btn btn-primary">Save session</button> <a class="btn btn-light" href="<?= base_url('school/admission/sessions') ?>">Cancel</a><?= form_close() ?></div></div></div>
<script>document.getElementById('admission-school').addEventListener('change',async function(){const data=await fetch('<?= base_url('school/admission/academic-data') ?>/'+this.value).then(r=>r.json());const target=document.getElementById('academic-year');target.innerHTML=data.years.map(x=>`<option value="${x.id}">${x.title}</option>`).join('');});</script>
